# Generated by Django 3.2.4 on 2022-01-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
