# Generated by Django 3.2.4 on 2022-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
